### ISSUE TITLE
missing set_multiple_pixels

### ISSUE THREAD

**Issue by dglaude** [pimoroni/led-shim#11]
The example set_multiple.py use a non existing feature.

It say:

> AttributeError: 'module' object has no attribute 'set_multiple_pixels'

```
pi@blinka:~/Pimoroni/ledshim/examples $ python2 set_multiple.py
Green
Traceback (most recent call last):
  File "set_multiple.py", line 8, in <module>
    ledshim.set_multiple_pixels(range(0, 28), (0, 255, 0))
AttributeError: 'module' object has no attribute 'set_multiple_pixels'
pi@blinka:~/Pimoroni/ledshim/examples $ python3 set_multiple.py
Green
Traceback (most recent call last):
  File "set_multiple.py", line 8, in <module>
    ledshim.set_multiple_pixels(range(0, 28), (0, 255, 0))
AttributeError: module 'ledshim' has no attribute 'set_multiple_pixels'
```

**Comment by fishgotnosole** [comment]
Also having exact same issue. Is there any word on a fix, please?

**Comment by baralong** [comment]
Also the same issue. It does exist in https://github.com/pimoroni/led-shim/blob/master/library/ledshim/__init__.py
Perhaps https://get.pimoroni.com/ledshim is getting an older version? Or the later version isn't packed?

**Comment by Gadgetoid** [comment]
Yup this library has slipped through the cracks somewhat, last release was v0.0.1 - https://pypi.org/project/ledshim/ - May 17th 2018 :scream: 

The fix was added two months later and has been in release purgatory for... a while.

On my immediate TODO list!


Edit: Should be fixed as of 0.0.2.

**Comment by baralong** [comment]
> Edit: Should be fixed as of 0.0.2.

Awesome, thanks. I'll test it out this evening, or tomorrow, at least when I get the chance. (regretting not bringing my pi to work ;) )
